# Generated by Django 5.0.6 on 2024-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_accountuser_account_user_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountuser',
            name='myapp_accou_account_d6f119_idx',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='account_user_email',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(default='yreza1903@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id'], name='myapp_accou_account_5b0109_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_related_user'], name='myapp_accou_account_52d18d_idx'),
        ),
    ]
