# Generated by Django 5.0.6 on 2024-06-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_accountuser_myapp_accou_account_5b0109_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='account_user_email',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
