# Generated by Django 5.0.6 on 2024-06-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_accountuser_account_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountuser',
            name='myapp_accou_account_d6f119_idx',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id'], name='myapp_accou_account_5b0109_idx'),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_related_user'], name='myapp_accou_account_52d18d_idx'),
        ),
    ]
