# Generated by Django 5.0.6 on 2024-06-14 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameIndex(
            model_name='accountuser',
            new_name='myapp_accou_account_5d0f2f_idx',
            old_name='myapp_accou_account_d6f119_idx',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
