# Generated by Django 5.0.6 on 2024-07-03 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_email_accountuser_account_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.UUID('9f33f28b-842a-486b-82f8-5fe174e1399d'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(editable=False, max_length=255)),
                ('course_created_by', models.CharField(max_length=255)),
                ('course_created_date', models.DateTimeField(auto_now_add=True)),
                ('course_updated_by', models.CharField(max_length=255, null=True)),
                ('course_updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('course_id',),
                'indexes': [models.Index(fields=['course_id'], name='myapp_cours_course__4e3bc2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendingCourse',
            fields=[
                ('attending_course_id', models.UUIDField(default=uuid.UUID('8293b857-0ab2-4631-bd7a-369b77008c35'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('attending_account_profile_id', models.CharField(editable=False, max_length=255)),
                ('attending_course_created_by', models.CharField(max_length=255)),
                ('attending_course_created_date', models.DateTimeField(auto_now_add=True)),
                ('attending_course_updated_by', models.CharField(max_length=255, null=True)),
                ('attending_course_updated_date', models.DateTimeField(auto_now_add=True)),
                ('attending_courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'ordering': ('attending_course_id',),
                'indexes': [models.Index(fields=['attending_course_id', 'attending_courseid'], name='myapp_atten_attendi_66ed4b_idx')],
            },
        ),
    ]
