# Generated by Django 5.0.6 on 2024-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_accountuser_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountuser',
            name='myapp_accou_account_5b0109_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountuser',
            name='myapp_accou_account_52d18d_idx',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='email',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account_user_email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id', 'account_user_related_user'], name='myapp_accou_account_d6f119_idx'),
        ),
    ]
