# Generated by Django 5.0.6 on 2024-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_accountuser_account_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='account_user_email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
