# Generated by Django 5.0.6 on 2024-06-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_accountuser_myapp_accou_account_d6f119_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='email',
            new_name='account_user_email',
        ),
    ]
